# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitstrap < Formula
  desc ""
  homepage "https://github.com/g4s8/gitstrap"
  version "2.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/g4s8/gitstrap/releases/download/v2.2/gitstrap_Darwin_x86_64.tar.gz"
      sha256 "a9be9602474f3b2fed931d9085452d01ecb6ab5389aae9da9f9219e94afe6e06"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/g4s8/gitstrap/releases/download/v2.2/gitstrap_Linux_x86_64.tar.gz"
      sha256 "32c4f5fd2b9a21b4f501a639027f3b35d9e3c3fb4246e68e51ec0dc48aab8b13"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/g4s8/gitstrap/releases/download/v2.2/gitstrap_Linux_arm64.tar.gz"
      sha256 "a1959e37ef8eb218b6a19bf8b048bd445d3b878963f04d889f6ecad5d9295955"
    end
  end

  depends_on "git"

  def install
    bin.install "gitstrap"
  end
end
