# This file was generated by GoReleaser. DO NOT EDIT.
class Reporter < Formula
  desc ""
  homepage "https://github.com/g4s8/reporter"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/g4s8/reporter/releases/download/0.1.1/reporter_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "42969c2d2b2ee2da88acc00dd16c767d5b6e0d2a059909ec133e82abf1dcf25b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/g4s8/reporter/releases/download/0.1.1/reporter_0.1.1_Linux_x86_64.tar.gz"
      sha256 "9430fcf0e80a6a6e48e689b783fbae6081e40debd5188a388fd9a40a069fad24"
    end
  end

  def install
    bin.install "reporter"
  end
end
