# This file was generated by GoReleaser. DO NOT EDIT.
class Wts < Formula
  desc ""
  homepage "https://github.com/g4s8/wts"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/g4s8/wts/releases/download/0.1.1/wts_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "1c37c36e0845972cca54e59daffb694950668033904a46d0ffb08216b08bb8fa"
  elsif OS.linux?
    url "https://github.com/g4s8/wts/releases/download/0.1.1/wts_0.1.1_Linux_x86_64.tar.gz"
    sha256 "bd86f227f32d1b716c6283483f5940ef8dede3f30438d744694d751e7a6384a9"
  end
  
  depends_on "git"

  def install
    bin.install "wts"
  end
end
